// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $index from "./routes/index.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $ProjectsFilter from "./islands/ProjectsFilter.tsx";
import * as $WorldMap from "./islands/WorldMap.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/index.tsx": $index,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Hero.tsx": $Hero,
    "./islands/ProjectsFilter.tsx": $ProjectsFilter,
    "./islands/WorldMap.tsx": $WorldMap,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
